### PR TITLE
First commit.

### PR DESCRIPTION
**Pull request by 4goodapp**

### CODE REVIEW

**Comment by D0miH** [comment]
Hey @4goodapp,
thanks for your PR! 👍🏼

I will look at it today or tomorrow  when I have time :)

**Comment by D0miH** [comment]
This site looks awesome👍🏼😁

Is it possible to add some kind of little arrow/triangle that is facing downward (see image)? This way the user would know that he can scroll to see more info.

Could you upload the whole grav project? So we can modify the site in the future.

Screenshot 2020-04-22 at 18 03 21

**Comment by D0miH** [comment]
Could you exchange the logo with the one that is used in the readme on the github page? Then we have a uniform look throughout all pages.

**Comment by 4goodapp** [comment]
> Is it possible to add some kind of little arrow/triangle that is facing downward (see image)?

Of course...

> Could you exchange the logo with the one that is used in the readme on the github page?

Of course.
btw, I'd like that we retouch the logo tho... I can do it if you want.

> Could you upload the whole grav project? So we can modify the site in the future.

Yes but, don't you think it's going to make project more complicated
as we don't need GRAV at all. What do you think?

**Comment by D0miH** [comment]
> btw, I'd like that we retouch the logo tho... I can do it if you want.
Yeah, you are right. Your logo also fits better with the font of the whole page.

> Yes but, don't you think it's going to make project more complicated as we don't need GRAV at all.
I see. So you want to manipulate the html directly?

**Comment by 4goodapp** [comment]
> So you want to manipulate the html directly?

Not sure what you mean there but I didn't use aby GRAV feature actually.
It was just for an easier integration of multiple languages.
Maybe there are some free hosting out there for open source project...

Otherwise we can just use English version and hosted on GitHubt Page
till. we find better options.

About the logo, what font is the current logo using?
It looks like Century Gothic but am not really sure.

**Comment by D0miH** [comment]
> Otherwise we can just use English version and hosted on GitHubt Page till. we find better options.

sure👍🏼

> About the logo, what font is the current logo using?

The font is called futura.

Concerning the content of the page I think for the first release it is ok to just list the features (see readme of the project) with a screenshot of one of the settings.
I think if all the buttons are pointing to the correct links, the little arrow is added and the site is filled with the content we can merge and deploy the site👍🏼😁

**Comment by 4goodapp** [comment]
Sorry, I missed the email.
About the screenshots and text content/festures, you can send them or?

**Comment by D0miH** [comment]
> Sorry, I missed the email. About the screenshots and text content/festures, you can send them or?

Sure I will prepare them and post them here within the next few days.

**Comment by D0miH** [comment]
Ok so here is the example screenshot for the cpu settings:
Screenshot 2020-04-30 at 16 52 58

The text with the features is the same as you have already added to the site:

### Features
- Display CPU utilization as a graph
- Read CPU temperature
- Monitor memory usage
- Monitor network usage
- Monitor fan speed
- Low and/or high battery notification at custom thresholds
- App adjusts to light & dark mode

**Comment by 4goodapp** [comment]
Perfect!

**Pull request closed without merging**
